=== nextstrain/augur/augur/data/schema-export-v1-meta.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "https://nextstrain.org/schemas/dataset/v1/meta",
    "type": "object",
    "title": "Nextstrain minimal metadata JSON schema",
    "description": "This is the validation schema for the augur produced metadata JSON, for consumption in Auspice. Note that every field is optional, but excluding fields may disable certain features in Auspice.",
    "additionalProperties": true,
    "properties" : {
        "title" : {
            "description": "Auspice displays this at the top of the page",
            "type" : "string"
        },
        "updated" : {
            "description": "Auspice displays this in the footer",
            "type" : "string"
        },
        "virus_count" : {
            "description": "Auspice uses this in the header info text and the status page. Should be renamed or deprecated for version 1.0",
            "type" : "number"
        },
        "author_info": {
            "description": "Used to display information about terminal nodes & for filtering by author (if \"authors\" is in \"filters\", see below)",
            "$comment": "Each key is typically an author name, e.g. \"Black et al\", and must exist in the attrs object of at least one terminal node of the tree",
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^.+$": {
                    "type": "object",
                    "additionalProperties": false,
                    "$comment": "in the future these properties may be required",
                    "properties": {
                        "n": {
                            "description": "Number of sequences / samples associated with this publication",
                            "type": "number"
                        },
                        "title": {
                            "description": "Publication title",
                            "type": "string"
                        },
                        "journal": {
                            "description": "Journal title",
                            "type": "string"
                        },
                        "paper_url": {
                            "description": "URL link to paper or NCBI genome. Use \"?\" if unknown",
                            "type": "string",
                            "oneOf": [
                                {"pattern": "^https?://.+$"},
                                {"enum": ["?"]}
                            ]
                        }
                    }
                }
            }
        },
        "annotations": {
            "description": "Genome annotations (e.g. genes), relative to the reference genome",
            "$comment": "Required for the entropy panel",
            "type": "object",
            "required": ["nuc"],
            "additionalProperties": false,
            "properties": {
                "nuc": {
                    "type": "object",
                    "properties": {
                        "start": {
                            "description": "Gene start position (zero-based, i.e. BED format)",
                            "type": "number"
                        },
                        "end": {
                            "description": "Gene end position (zero-based half open, i.e. BED format)",
                            "type": "number"
                        },
                        "strand": {
                            "description": "Positive or negative strand",
                            "type": "number",
                            "enum": [-1, 1]
                        }
                    }
                }
            },
            "patternProperties": {
                "^[a-zA-Z0-9*_-]+$": {"$ref": "#/properties/annotations/properties/nuc"}
            }
        },
        "maintainer": {
            "description": "Auspice displays the maintainer in the footer",
            "type": "array",
            "items": [
                {
                    "type": "string",
                    "description": "Text displayed in the browser"
                },
                {
                    "type": "string",
                    "description": "href for the text. E.g. mailto:, twitter link, lab website"
                }
            ]
        },
        "filters": {
            "description": "These appear as filters in the footer of Auspice (which populates the displayed values based upon the tree)",
            "$comment": "These values must be present as keys on the attr of nodes on the tree",
            "type": "array",
            "uniqueItems": true,
            "items": {"type": "string"}
        },
        "panels": {
            "description": "Which panels should Auspice display?",
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["tree", "map", "frequencies", "entropy"]
            },
            "uniqueItems": true,
            "minItems": 1
        },
        "geo": {
            "description": "The available options for the geographic resolution dropdown",
            "type": "object",
            "patternProperties": {
                "^[a-z]*$": {
                    "description": "The names of the geographic resolutions",
                    "$comment": "E.g. country or region. These need to be present as keys in the attrs of the tree nodes",
                    "type": "object",
                    "patternProperties": {
                        "^[a-z_]*$": {
                            "description": "The values (of the demes) for this geographic resolutions",
                            "$comment": "E.g. Brazil, China etc. The tree nodes must contain these as values of the geographic resolution key",
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                                "latitude": {
                                    "type": "number",
                                    "minimum": -180,
                                    "maximum": 180
                                },
                                "longitude": {
                                    "type": "number",
                                    "minimum": -180,
                                    "maximum": 180
                                }
                            }
                        }
                    }
                }
            }
        },
        "color_options": {
            "description": "Available colorBys for Auspice",
            "$comment": "These properties need to be present as keys in the attrs of the tree nodes",
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[A-Za-z_]*$": {
                    "description": "property name is the key used on the tree node attrs",
                    "type": "object",
                    "properties": {
                        "key": {
                            "description": "???",
                            "type": "string"
                        },
                        "menuItem": {
                            "description": "Text to be displayed in the \"color by\" dropdown menu",
                            "type": "string"
                        },
                        "legendTitle": {
                            "description": "Text to be displayed in the \"color by\" tree menu",
                            "type": "string"
                        },
                        "type": {
                            "description": "Dictates how the color scale should be made",
                            "type": "string",
                            "enum": ["continuous", "discrete"]
                        },
                        "color_map": {
                            "description": "Links values to colors. Enforces a discrete scale, no matter what the \"type\" property is.",
                            "$comment": "A greyscale ramp will be used for missing values (i.e. defined on the tree but not here)",
                            "type": "array",
                            "uniqueItems": true,
                            "items": {
                                "type": "array",
                                "additionalItems": false,
                                "items": [
                                    {
                                        "description": "value (tree nodes -> attrs -> propertyName)",
                                        "type": "string",
                                        "pattern": "^[ 0-9A-Za-z_.-]+$"
                                    },
                                    {
                                        "description": "color hex value",
                                        "type": "string",
                                        "pattern": "^#[0-9A-Fa-f]{6}$"
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "defaults": {
            "description": "Set the defaults for certain display options in Auspice. All are optional.",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "geoResolution": {
                    "description": "Default geographic resolution",
                    "$comment": "The value here must be present in the geo object (see above)",
                    "type": "string"
                },
                "colorBy": {
                    "description": "Default color by",
                    "$comment": "The value here must be present in the color_options object (see above)",
                    "type": "string"
                },
                "distanceMeasure": {
                    "description": "Default tree metric",
                    "type": "string",
                    "enum": ["div", "num_date"]
                },
                "mapTriplicate": {
                    "description": "Should the map be extended / wrapped around. Useful if transmissions are worldwide.",
                    "type": "boolean"
                }
            }
        },
        "commit": {
            "description": "Augur commit used to prepare these JSONs",
            "$comment": "DEPRECATED. Will be replaced with version in 0.1",
            "type": "string"
        },
        "controls": {
            "$comment": "DEPRECATED"
        },
        "seq_author_map": {
            "$comment": "DEPRECATED"
        },
        "vaccine_choices": {
            "description": "Vaccine strains displayed in Auspice",
            "type": "object",
            "patternProperties": {
                "^.+$": {
                    "description": "Strain names",
                    "$comment": "must exist as a strain name on the tree. Currently the value is unused.",
                    "type": "string",
                    "pattern": "^[0-9X]{4}-[0-9X]{2}-[0-9X]{2}$"
                }
            }
        }
    }
}

=== nextstrain/augur/tests/cli/validate/tb/export_v1/in/tb_meta.json
{
  "annotations": {
    "*MtCM": {
      "end": 2134872,
      "start": 2134272,
      "strand": 1
    },
    "PE13": {
      "end": 1339302,
      "start": 1339002,
      "strand": 1
    },
    "PE_PGRS39": {
      "end": 2618908,
      "start": 2617666,
      "strand": 1
    },
    "PE_PGRS60": {
      "end": 4093946,
      "start": 4093631,
      "strand": 1
    },
    "PPE13": {
      "end": 978203,
      "start": 976871,
      "strand": 1
    },
    "PPE20": {
      "end": 1563388,
      "start": 1561768,
      "strand": 1
    },
    "PPE50": {
      "end": 3501732,
      "start": 3501333,
      "strand": 1
    },
    "Rv0010c": {
      "end": 13558,
      "start": 13132,
      "strand": 1
    },
    "Rv0011c": {
      "end": 13995,
      "start": 13713,
      "strand": 1
    },
    "Rv0026": {
      "end": 31068,
      "start": 29721,
      "strand": 1
    },
    "Rv0039c": {
      "end": 42351,
      "start": 42003,
      "strand": 1
    },
    "Rv0147": {
      "end": 174758,
      "start": 173237,
      "strand": 1
    },
    "Rv0323c": {
      "end": 391251,
      "start": 390579,
      "strand": 1
    },
    "Rv0401": {
      "end": 480160,
      "start": 479788,
      "strand": 1
    },
    "Rv0466": {
      "end": 557252,
      "start": 556457,
      "strand": 1
    },
    "Rv0565c": {
      "end": 657470,
      "start": 656009,
      "strand": 1
    },
    "Rv0600c": {
      "end": 698410,
      "start": 697903,
      "strand": 1
    },
    "Rv0605": {
      "end": 702014,
      "start": 701405,
      "strand": 1
    },
    "Rv0744c": {
      "end": 834946,
      "start": 834439,
      "strand": 1
    },
    "Rv0745": {
      "end": 835681,
      "start": 835153,
      "strand": 1
    },
    "Rv0841": {
      "end": 937835,
      "start": 937592,
      "strand": 1
    },
    "Rv0879c": {
      "end": 978756,
      "start": 978480,
      "strand": 1
    },
    "Rv0893c": {
      "end": 996295,
      "start": 995317,
      "strand": 1
    },
    "Rv0909": {
      "end": 1014860,
      "start": 1014680,
      "strand": 1
    },
    "Rv0920c": {
      "end": 1026816,
      "start": 1025496,
      "strand": 1
    },
    "Rv0921": {
      "end": 1027685,
      "start": 1027103,
      "strand": 1
    },
    "Rv1042c": {
      "end": 1165499,
      "start": 1165091,
      "strand": 1
    },
    "Rv1043c": {
      "end": 1166806,
      "start": 1165780,
      "strand": 1
    },
    "Rv1081c": {
      "end": 1206418,
      "start": 1205983,
      "strand": 1
    },
    "Rv1096": {
      "end": 1225260,
      "start": 1224384,
      "strand": 1
    },
    "Rv1112": {
      "end": 1239328,
      "start": 1238254,
      "strand": 1
    },
    "Rv1129c": {
      "end": 1254534,
      "start": 1253073,
      "strand": 1
    },
    "Rv1144": {
      "end": 1271908,
      "start": 1271155,
      "strand": 1
    },
    "Rv1192": {
      "end": 1335754,
      "start": 1334926,
      "strand": 1
    },
    "Rv1194c": {
      "end": 1338513,
      "start": 1337247,
      "strand": 1
    },
    "Rv1218c": {
      "end": 1362733,
      "start": 1361797,
      "strand": 1
    },
    "Rv1303": {
      "end": 1460251,
      "start": 1459765,
      "strand": 1
    },
    "Rv1393c": {
      "end": 1569587,
      "start": 1568108,
      "strand": 1
    },
    "Rv1465": {
      "end": 1653256,
      "start": 1652767,
      "strand": 1
    },
    "Rv1482c": {
      "end": 1673299,
      "start": 1672456,
      "strand": 1
    },
    "Rv1520": {
      "end": 1712068,
      "start": 1711027,
      "strand": 1
    },
    "Rv1816": {
      "end": 2058960,
      "start": 2058255,
      "strand": 1
    },
    "Rv1817": {
      "end": 2061058,
      "start": 2059594,
      "strand": 1
    },
    "Rv1939": {
      "end": 2192609,
      "start": 2192093,
      "strand": 1
    },
    "Rv2077c": {
      "end": 2334294,
      "start": 2333322,
      "strand": 1
    },
    "Rv2209": {
      "end": 2474938,
      "start": 2473399,
      "strand": 1
    },
    "Rv2314c": {
      "end": 2587290,
      "start": 2585916,
      "strand": 1
    },
    "Rv2417c": {
      "end": 2716314,
      "start": 2715471,
      "strand": 1
    },
    "Rv2729c": {
      "end": 3042475,
      "start": 3041569,
      "strand": 1
    },
    "Rv2733c": {
      "end": 3046524,
      "start": 3044985,
      "strand": 1
    },
    "Rv2734": {
      "end": 3047675,
      "start": 3046820,
      "strand": 1
    },
    "Rv2752c": {
      "end": 3066191,
      "start": 3064514,
      "strand": 1
    },
    "Rv2765": {
      "end": 3075373,
      "start": 3074635,
      "strand": 1
    },
    "Rv2771c": {
      "end": 3081033,
      "start": 3080580,
      "strand": 1
    },
    "Rv2807": {
      "end": 3114812,
      "start": 3113657,
      "strand": 1
    },
    "Rv2885c": {
      "end": 3195548,
      "start": 3194165,
      "strand": 1
    },
    "Rv3067": {
      "end": 3431838,
      "start": 3431427,
      "strand": 1
    },
    "Rv3071": {
      "end": 3435573,
      "start": 3434463,
      "strand": 1
    },
    "Rv3087": {
      "end": 3454343,
      "start": 3452924,
      "strand": 1
    },
    "Rv3090": {
      "end": 3459098,
      "start": 3458210,
      "strand": 1
    },
    "Rv3210c": {
      "end": 3587539,
      "start": 3586843,
      "strand": 1
    },
    "Rv3463": {
      "end": 3881764,
      "start": 3880906,
      "strand": 1
    },
    "Rv3651": {
      "end": 4092878,
      "start": 4091840,
      "strand": 1
    },
    "Rv3766": {
      "end": 4212982,
      "start": 4212292,
      "strand": 1
    },
    "Rv3863": {
      "end": 4340027,
      "start": 4338848,
      "strand": 1
    },
    "ahpC": {
      "end": 2726780,
      "start": 2726192,
      "strand": 1
    },
    "atsH": {
      "end": 4251005,
      "start": 4249877,
      "strand": 1
    },
    "blaC": {
      "end": 2326809,
      "start": 2325885,
      "strand": 1
    },
    "cinA": {
      "end": 2148954,
      "start": 2147661,
      "strand": 1
    },
    "cobS": {
      "end": 2473242,
      "start": 2472492,
      "strand": 1
    },
    "ctpE": {
      "end": 1014124,
      "start": 1011730,
      "strand": 1
    },
    "cycA": {
      "end": 1931456,
      "start": 1929785,
      "strand": 1
    },
    "cyp141": {
      "end": 3487711,
      "start": 3486508,
      "strand": 1
    },
    "cysE": {
      "end": 2610421,
      "start": 2609731,
      "strand": 1
    },
    "dlaT": {
      "end": 2483626,
      "start": 2481964,
      "strand": 1
    },
    "dnaQ": {
      "end": 4156729,
      "start": 4155739,
      "strand": 1
    },
    "eccC2": {
      "end": 4380452,
      "start": 4376261,
      "strand": 1
    },
    "eccD1": {
      "end": 4356542,
      "start": 4355006,
      "strand": 1
    },
    "echA8": {
      "end": 1195043,
      "start": 1194269,
      "strand": 1
    },
    "eis": {
      "end": 2715332,
      "start": 2714123,
      "strand": 1
    },
    "embA": {
      "end": 4246517,
      "start": 4243232,
      "strand": 1
    },
    "embB": {
      "end": 4249810,
      "start": 4246513,
      "strand": 1
    },
    "embC": {
      "end": 4243147,
      "start": 4239862,
      "strand": 1
    },
    "espB": {
      "end": 4361925,
      "start": 4360542,
      "strand": 1
    },
    "espG2": {
      "end": 4373630,
      "start": 4372799,
      "strand": 1
    },
    "esxA": {
      "end": 4352896,
      "start": 4352608,
      "strand": 1
    },
    "esxB": {
      "end": 4352576,
      "start": 4352273,
      "strand": 1
    },
    "esxC": {
      "end": 4374013,
      "start": 4373725,
      "strand": 1
    },
    "esxD": {
      "end": 4374372,
      "start": 4374048,
      "strand": 1
    },
    "esxE": {
      "end": 4390709,
      "start": 4390436,
      "strand": 1
    },
    "esxF": {
      "end": 4391031,
      "start": 4390719,
      "strand": 1
    },
    "esxG": {
      "end": 351818,
      "start": 351524,
      "strand": 1
    },
    "esxH": {
      "end": 352138,
      "start": 351847,
      "strand": 1
    },
    "esxI": {
      "end": 1160828,
      "start": 1160543,
      "strand": 1
    },
    "esxJ": {
      "end": 1161151,
      "start": 1160854,
      "strand": 1
    },
    "esxK": {
      "end": 1340955,
      "start": 1340658,
      "strand": 1
    },
    "esxL": {
      "end": 1341290,
      "start": 1341005,
      "strand": 1
    },
    "esxM": {
      "end": 2030643,
      "start": 2030346,
      "strand": 1
    },
    "esxN": {
      "end": 2030978,
      "start": 2030693,
      "strand": 1
    },
    "esxO": {
      "end": 2626172,
      "start": 2625887,
      "strand": 1
    },
    "esxP": {
      "end": 2626519,
      "start": 2626222,
      "strand": 1
    },
    "esxQ": {
      "end": 3376852,
      "start": 3376489,
      "strand": 1
    },
    "esxR": {
      "end": 3379001,
      "start": 3378710,
      "strand": 1
    },
    "esxS": {
      "end": 3379329,
      "start": 3379035,
      "strand": 1
    },
    "esxT": {
      "end": 3862926,
      "start": 3862623,
      "strand": 1
    },
    "esxU": {
      "end": 3863264,
      "start": 3862946,
      "strand": 1
    },
    "esxV": {
      "end": 4060268,
      "start": 4059983,
      "strand": 1
    },
    "esxW": {
      "end": 4060591,
      "start": 4060294,
      "strand": 1
    },
    "ethA": {
      "end": 4327473,
      "start": 4326003,
      "strand": 1
    },
    "fabG1": {
      "end": 1674183,
      "start": 1673439,
      "strand": 1
    },
    "fadA2": {
      "end": 293493,
      "start": 292170,
      "strand": 1
    },
    "fadA3": {
      "end": 1199373,
      "start": 1198155,
      "strand": 1
    },
    "fadA4": {
      "end": 1487031,
      "start": 1485861,
      "strand": 1
    },
    "fadA5": {
      "end": 3986732,
      "start": 3985556,
      "strand": 1
    },
    "fadA6": {
      "end": 3996964,
      "start": 3995803,
      "strand": 1
    },
    "fadD14": {
      "end": 1182315,
      "start": 1180683,
      "strand": 1
